/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContainerControls: typeof import('./src/components/playground/ContainerControls.vue')['default']
    CssOutput: typeof import('./src/components/playground/CssOutput.vue')['default']
    DemoStage: typeof import('./src/components/playground/DemoStage.vue')['default']
    ItemControls: typeof import('./src/components/playground/ItemControls.vue')['default']
    ItemList: typeof import('./src/components/playground/ItemList.vue')['default']
    MetricsTable: typeof import('./src/components/playground/MetricsTable.vue')['default']
    OverlayLayer: typeof import('./src/components/playground/OverlayLayer.vue')['default']
    PropertyField: typeof import('./src/components/playground/PropertyField.vue')['default']
    StageResizer: typeof import('./src/components/playground/StageResizer.vue')['default']
    ThePlayground: typeof import('./src/components/playground/ThePlayground.vue')['default']
    TrapDiff: typeof import('./src/components/traps/TrapDiff.vue')['default']
    TrapSection: typeof import('./src/components/traps/TrapSection.vue')['default']
    TrapsSection: typeof import('./src/components/traps/TrapsSection.vue')['default']
    TrapStage: typeof import('./src/components/traps/TrapStage.vue')['default']
  }
}
